apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-config
  namespace: default
data:
  default.yml: |
    splunk:
      conf:
        server:
          content:
            diskUsage:
              minFreeSpace: 1000
        indexes:
          directory: /opt/splunk/etc/apps/search/local
          content:
            kafka:
              coldPath: $SPLUNK_DB/kafka/colddb
              datatype: event
              homePath: $SPLUNK_DB/kafka/db
              maxTotalDataSizeMB: 512000
              thawedPath: $SPLUNK_DB/kafka/thaweddb
            kafka-header-index:
              coldPath: $SPLUNK_DB/kafka-header-index/colddb
              datatype: event
              homePath: $SPLUNK_DB/kafka-header-index/db
              maxTotalDataSizeMB: 512000
              thawedPath: $SPLUNK_DB/kafka-header-index/thaweddb
---
apiVersion: v1
kind: Pod
metadata:
  name: splunk
  labels:
    app: splunk
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: splunk
      image: docker.io/__SPLUNK_IMAGE__
      ports:
        - name: web-interface
          containerPort: 8000
          protocol: TCP
        - name: hec
          containerPort: 8088
          protocol: TCP
        - name: management-api
          containerPort: 8089
          protocol: TCP
      env:
        - name: SPLUNK_GENERAL_TERMS
          value: --accept-sgt-current-at-splunk-com
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_USER
          value: root
        - name: SPLUNK_PASSWORD
          value: __SPLUNK_PASSWORD__
        - name: SPLUNK_LAUNCH_CONF
          value: OPTIMISTIC_ABOUT_FILE_LOCKING=1
        - name: SPLUNK_HEC_TOKEN
          value: __SPLUNK_HEC_TOKEN__
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          memory: 2Gi
      readinessProbe:
        tcpSocket:
          port: 8089
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 8089
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 5
      volumeMounts:
        - name: config-volume
          mountPath: /tmp/defaults/
  volumes:
    - name: config-volume
      configMap:
        name: splunk-config
