apiVersion: v2
name: splunk-opentelemetry-collector-for-kafka
description: Splunk OpenTelemetry Collector for Kafka (SOC4Kafka) - collects Kafka messages and forwards them to Splunk HEC
type: application
version: 0.145.0
appVersion: "0.145.0"
keywords:
  - splunk
  - kafka
  - opentelemetry
  - logs
  - hec
maintainers:
  - name: Splunk
    url: https://github.com/splunk/splunk-opentelemetry-collector-for-kafka
sources:
  - https://github.com/splunk/splunk-opentelemetry-collector-for-kafka
kubeVersion: ">=1.19.0"
