---
site_name: Splunk OpenTelemetry Collector for Kafka (SOC4Kafka)
site_url: https://splunk.github.io/splunk-opentelemetry-collector-for-kafka/

repo_url: https://github.com/splunk/splunk-opentelemetry-collector-for-kafka
repo_name: splunk/splunk-opentelemetry-collector-for-kafka
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
  - smarty
  - fenced_code
  - sane_lists
  - codehilite
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true

plugins:
  - search:
      lang: en

extra_javascript:
  - javascripts/footer.js

copyright: <p>Webpages built on GitHub Pages | <a href="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service">Github Terms</a> | <a href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">GitHub Privacy</a></p>

theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"

nav:
  - Collector for Kafka: "index.md"
  - Design: "ia-refactor/collector-for-kafka-design.md"
  - Deploy:
      - Overview: "ia-refactor/collector-for-kafka-deploy.md"
      - Kubernetes:
          - Overview: "ia-refactor/collector-for-kafka-kubernetes.md"
          - Install with Helm: "ia-refactor/collector-for-kafka-kubernetes-install-helm.md"
          - Configure the Helm chart: "ia-refactor/collector-for-kafka-kubernetes-configure-helm.md"
          - Troubleshoot the Helm deployment: "ia-refactor/collector-for-kafka-kubernetes-troubleshoot-helm.md"
          - Upgrade with Helm: "ia-refactor/collector-for-kafka-kubernetes-upgrade-helm.md"
          - Uninstall with Helm: "ia-refactor/collector-for-kafka-kubernetes-uninstall-helm.md"
      - Ansible:
          - Overview: "ia-refactor/collector-for-kafka-ansible.md"
          - Install: "ia-refactor/collector-for-kafka-ansible-install.md"
          - Configure: "ia-refactor/collector-for-kafka-ansible-configure.md"
          - Troubleshoot: "ia-refactor/collector-for-kafka-ansible-troubleshoot.md"
          - Upgrade: "ia-refactor/collector-for-kafka-ansible-upgrade.md"
          - Uninstall: "ia-refactor/collector-for-kafka-ansible-uninstall.md"
      - Manual:
          - Overview: "ia-refactor/collector-for-kafka-manual.md"
          - Install: "ia-refactor/collector-for-kafka-manual-install.md"
      - OCI Streaming: "ia-refactor/collector-for-kafka-oci-streaming.md"
  - Configure:
      - Overview: "ia-refactor/collector-for-kafka-configure.md"
      - Secrets: "ia-refactor/collector-for-kafka-configure-secrets.md"
      - TLS: "ia-refactor/collector-for-kafka-configure-tls.md"
      - Examples: "ia-refactor/collector-for-kafka-configure-examples.md"
      - Advanced configuration:
          - Overview: "ia-refactor/collector-for-kafka-configure-advanced.md"
          - Multiple topics: "ia-refactor/collector-for-kafka-configure-multiple-topics.md"
          - Regex topics: "ia-refactor/collector-for-kafka-configure-regex-topics.md"
          - Extract data: "ia-refactor/collector-for-kafka-configure-extract-data.md"
  - Operate:
      - Overview: "ia-refactor/collector-for-kafka-operate.md"
      - Scale: "ia-refactor/collector-for-kafka-scale.md"
      - Load balancing: "ia-refactor/collector-for-kafka-load-balance.md"
      - Troubleshooting: "ia-refactor/collector-for-kafka-troubleshoot.md"
  - Monitor:
      - Overview: "ia-refactor/collector-for-kafka-monitor.md"
      - Dashboard: "ia-refactor/collector-for-kafka-dashboard.md"
      - Collector logs: "ia-refactor/collector-for-kafka-collector-logs.md"
  - Migrate from Splunk Connect for Kafka:
      - Overview: "ia-refactor/collector-for-kafka-migrate-from-sc4kafka.md"
      - Configuration mapping: "ia-refactor/collector-for-kafka-migrate-config.md"
      - Examples: "ia-refactor/collector-for-kafka-migrate-examples.md"
      - Strategy: "ia-refactor/collector-for-kafka-migrate-strategy.md"
