---
- hosts: localhost

  vars:
    # Set to true to upgrade SOC4Kafka binary if it already exists
    upgrade_soc4kafka: true

    # Operating System information
    # Choose from:
    # linux, darwin (= macOS)
    operating_system: "linux"
    # Choose from:
    # amd64, arm64
    architecture: "amd64"

    # Kafka and Splunk HEC configuration
    brokers: "broker1:port1,broker2:port2"
    topic: "example-topic"
    encoding: "text"
    insecure_skip_verify: false  # Set to true to skip TLS verification (not recommended for production)
    splunk_hec_token: "your-splunk-hec-token"
    splunk_hec_endpoint: "https://splunk-hec-endpoint:8088/services/collector"
    source: "example-source"
    sourcetype: "example-sourcetype"
    splunk_index: "example-index"

  tasks:
    - name: Check Splunk HEC connectivity
      uri:
        url: "{{ splunk_hec_endpoint }}"
        method: POST
        headers:
          Authorization: "Splunk {{ splunk_hec_token }}"
          Content-Type: "application/json"
        body: |
          {
            "event": "Quickstart check. SOC4Kafka to Splunk HEC test event",
            "sourcetype": "{{ sourcetype }}",
            "source": "{{ source }}",
            "index": "{{ splunk_index }}"
          }
        body_format: json
        status_code: 200,201,202
        validate_certs: no

    - name: Set binary destination path
      set_fact:
        otel_binary_file_name: "otelcol_{{ operating_system | lower }}_{{ architecture | lower }}"


    - name: Remove existing otel collector binary if upgrading SOC4Kafka
      file:
        path: "./{{ otel_binary_file_name }}"
        state: absent
      when: upgrade_soc4kafka

    - name: Set download URL based on OS and architecture
      set_fact:
        otel_download_url: https://github.com/signalfx/splunk-otel-collector/releases/latest/download/{{ otel_binary_file_name }}

    - name: Download correct otel collector binary
      get_url:
        url: "{{ otel_download_url }}"
        dest: "./{{ otel_binary_file_name }}"
        mode: '0744'


    - name: Download SOC4Kafka configuration file
      get_url:
        url: "https://github.com/splunk/splunk-opentelemetry-collector-for-kafka/blob/main/quickstart/templates/basic_conf_tmpl.yaml.j2"
        dest: "./values.yaml.j2"
        mode: '0644'

    - name: Generate values.yaml from template
      template:
        src: values.yaml.j2
        dest: ./values.yaml
        mode: '0644'

    - name: Display command to start the process
      debug:
        msg: "Run the following command to start the SOC4Kafka Collector: ./{{ otel_binary_file_name }} --config values.yaml"
