{{- range .Values.splunkExporters }}
{{- if and .token (not (hasPrefix "${" .token)) (not .secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-hec-%s" (include "soc4kafka.fullname" $) .name }}
  labels:
    {{- include "soc4kafka.labels" $ | nindent 4 }}
type: Opaque
data:
  splunk-hec-token: {{ .token | b64enc }}
---
{{- end }}
{{- end }}
{{- if and .Values.collectorLogs.enabled .Values.collectorLogs.forwardToSplunk.enabled }}
{{- if and .Values.collectorLogs.forwardToSplunk.token (not (hasPrefix "${" .Values.collectorLogs.forwardToSplunk.token)) (not .Values.collectorLogs.forwardToSplunk.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-hec-internal-logs" (include "soc4kafka.fullname" $) }}
  labels:
    {{- include "soc4kafka.labels" $ | nindent 4 }}
type: Opaque
data:
  splunk-hec-token: {{ .Values.collectorLogs.forwardToSplunk.token | b64enc }}
---
{{- end }}
{{- end }}