{{- if and (not .Values.existingSecret) .Values.splunk.hec.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soc4kafka.fullname" . }}-hec
  labels:
    {{- include "soc4kafka.labels" . | nindent 4 }}
type: Opaque
stringData:
  splunk-hec-token: {{ .Values.splunk.hec.token | quote }}
{{- end }}
