{{- range .Values.splunkExporters }}
{{- if and .token (not .secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-hec-%s" (include "soc4kafka.fullname" $) .name }}
  labels:
    {{- include "soc4kafka.labels" $ | nindent 4 }}
type: Opaque
data:
  splunk-hec-token: {{ .token | b64enc }}
---
{{- end }}
{{- end }}