{{- if not .Values.existingSecret }}
{{- $secretNeeded := false }}
{{- range .Values.splunkExporters }}
  {{- if and .token (not (hasPrefix "${" .token)) }}
    {{- $secretNeeded = true }}
  {{- end }}
{{- end }}
{{- if $secretNeeded }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soc4kafka.fullname" . }}-hec
  labels:
    {{- include "soc4kafka.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.splunkExporters }}
  {{- if and .token (not (hasPrefix "${" .token)) }}
  splunk-hec-token-{{ .name }}: {{ .token | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}