name: docs

on:
  push:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configure Git
        run: git config user.name "$GITHUB_ACTOR" && git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install docs dependencies
        run: pip install -r requirements-docs.txt

      - name: Determine chart version
        id: version
        run: |
          VERSION=$(grep '^version:' helm-chart/splunk-opentelemetry-collector-for-kafka/Chart.yaml | awk '{print $2}')
          echo "version=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Deploy docs
        run: |
          mike deploy --push --update-aliases "${{ steps.version.outputs.version }}" main
          mike set-default --push main
