name: Splunk Otel Kafka Connector Functional Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.24.4
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2



jobs:
  functional-test:
    runs-on: ubuntu-latest
    env:
      CI_SPLUNK_VERSION: 9.4.1
      CI_SPLUNK_HOST: localhost
      CI_SPLUNK_USERNAME: admin
      CI_SPLUNK_HEC_TOKEN: "00000000-0000-0000-0000-0000000000000"
      CI_SPLUNK_PASSWORD: helloworld
      CI_SPLUNK_MGMT_PORT: 8089
      CI_KAFKA_BROKER_ADDRESS: "localhost:9092"
      CI_OTEL_BINARY_FILE: "otelcol_linux_amd64"
      CI_SPLUNK_INDEX: kafka
      CI_SPLUNK_HEADER_TEST_INDEX: kafka-header-index

    steps:
      - uses: ./.github/workflows/actions/setup_env
      - name: Run Tests
        working-directory: tests
        run: |
          go test ./functional_tests/functional_test.go -v -timeout 10m