name: Create Release

on:
  push:
    branches:
      - main
jobs:
  create_release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Prepare release v')
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm-chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          RELEASE_TAG="splunk-opentelemetry-collector-for-kafka-${VERSION}"
          gh release edit "$RELEASE_TAG" \
            --notes "This SOC4Kafka release adopts [the Splunk OpenTelemetry Collector v${VERSION}](https://github.com/signalfx/splunk-otel-collector/releases/tag/v${VERSION})"
